Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metris/ClassLength:
  Enabled: false

Lint/UnusedMethodArgument:
  Exclude:
    - lib/sparse_matrix.rb
    - lib/diagonal_matrix.rb

Naming/UncommunicativeMethodParamName:
  Exclude:
    - lib/diagonal_matrix.rb

