Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metris/ClassLength:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Metrics/LineLength:
  Enabled: false
