language: ruby
sudo: false
dist: trusty

rvm: 2.5.3

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      before_install:
        - gem install rubocop
      script:
        - rubocop
    - stage: test
      before_install:
        - gem install test-unit
      script:
        - ruby test/sparse_matrix.rb
